name: Deploy to Vercel

on:
  workflow_run:
    workflows: ["CI Pipeline"] 
    types:
      - completed

jobs:
  deploy-frontend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy
        run: curl -X POST "$VERCEL_DEPLOY_HOOK"
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}

#  deploy-backend:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
#    runs-on: ubuntu-latest
#    needs: deploy-frontend 
#    steps:
#      - name: Deploy Backend to Railway
#        run: curl -X POST "$RAILWAY_DEPLOY_HOOK"
#        env:
#          RAILWAY_DEPLOY_HOOK: ${{ secrets.RAILWAY_DEPLOY_HOOK }